title: I'm Nila , Web Developer
author: Nila
email: your-email@domain.com
description: > # Web Developer

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  nazamini

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
